# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yz', '0003_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='college',
        ),
        migrations.DeleteModel(
            name='person',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
